### ISSUE TITLE
Fail on TL2020

### ISSUE THREAD

**Issue by aminophen** [munepi/bibunsho7-patch#5]
https://oku.edu.mie-u.ac.jp/tex/mod/forum/discuss.php?d=2839

あちらにコメントした通りで公式にはサポート外だとは思いますが，内蔵された cjk-gs-integrate が外のデータベースファイルを見つけてしまうのが一因だと思います。

kpsewhich -format=miscfont [データベースファイル名]

今後もデータベースファイルの syntax を拡張する可能性がありますので，内蔵データベースだけを探すように出来れば幸せ😊です。

**Comment by munepi** [comment]
@aminophen v1.5で対応しました。ひとまず、同梱する cjk-gs-support, jfontmaps を更新することにしました。
 * cjk-gs-support: synced to 20200307.0
 * jfontmaps: synced to 20200217.0
